### ISSUE TITLE
DUDA PRINCIPIANTE CHEEVOSFILTER

### ISSUE THREAD

**Issue by varodj** [rendakiro/CheevosFilter#1]

**Comment by varodj** [comment]
Hola Alfonoso, solo he logrado clonar en mi ordenador los codigos de CHEEVOS FILTER y los del RALIBRETO, pero despues ya nose continuar, para que me aparezcan las carpetas de cada sistema donde meter las roms. Tengo el PYTON3 instalado en mi pc, y clono los repositorios con GITHUB DESKTOP. Necesito una guia paso a paso porfavor. Muchas gracias!

**Comment by rendakiro** [comment]
# Como ejecutar CheevosFilter paso a paso

## Descargar el codigo de github
Primero descargar el codigo y recuerda tambien bajar el (RALibretro)[https://github.com/RetroAchievements/RALibretro/], para este ejemplo usare **RAHasher-x64-Linux-1.6.1.zip**

Una vez descargado pon el archivo **RAHasher junto al main.py**, si usas **windows asegurare de quitarle la extension**.

## Ejecución Inicial
Nos vamos con el terminal a la ubicación del código y **ejecutamos el main.py**, si todo va bien nos creara las carpetas 

```shell
python3 main.py

Carpetas para ROMS generadas.
Presiona cualquier tecla para cerrar....
```

En caso de que falle el RALibretro, también nos avisara.

```shell
python3 main.py

es neceario RAHasher
```

Una vez generadas las carpetas, metemos las roms que **quieremos analizar dentro de /roms/sistema**, en este ejemplo sera unos titulos de gba, siendo /toms/gba.

## Filtrado
Teniendo ya las carpetas generadas y las roms listas, **con conexion a internet**, volvemos a **ejecutar main.py**

El sistema se conectara a internet, bajara unos archivos de *retroarchivements* y comprobara las roms, **en caso positivo lo indicara en pantalla**.

```shell
python3 main.py

Sistema con Roms: gba
Juego reconocido: Pokemon - Edicion Rubi (Spain) (Rev 1).gba
Juego reconocido: Final Fantasy I & II - Dawn of Souls (USA).gba
Juego reconocido: WarioWare - Twisted! (USA, Australia).gba
Juego reconocido: Yoshi Topsy-Turvy (USA).gba
Juego reconocido: Final Fantasy VI Advance (Europe) (En,Fr,De,Es,It).gba
Logros En: Pokemon - Edicion Rubi (Spain) (Rev 1).gba
Logros En: Final Fantasy I & II - Dawn of Souls (USA).gba
Logros En: WarioWare - Twisted! (USA, Australia).gba
Logros En: Yoshi Topsy-Turvy (USA).gba
Logros En: Final Fantasy VI Advance (Europe) (En,Fr,De,Es,It).gba
Presiona cualquier tecla para cerrar....
```

Las **roms con logros**, se moverán a la carpeta **/clean/sistema,** en este caso /clean/gba, las que no tenga permanecen en /roms.

**Comment by varodj** [comment]
Muchas gracias Alfonso, siguiendo tus pasos he logrado que funcione desde windows. Te agradezco mucho esta aclaración y el desarrollo de este filtro, ya que hasta ahora era una tarea que la hacia de forma manual.
